### ISSUE TITLE
Cannot render table

### ISSUE THREAD

**Issue by theadanielskocher** [micromark/micromark-extension-gfm-table#12]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.0.0

### Link to runnable example

https://codepen.io/nguyen-dinh-hai-dang/pen/QWoJaza

### Steps to reproduce

The code in codepen works, but when I apply the code to my markdown editor, when I type the formula to create the table, the web page disappears, and I have to F5 to return to the original web page, and the part I wrote. is then erased.

### Expected behavior

Print the table

### Actual behavior

The web disappear, and I have to F5 to return to the original web page.

![image](https://github.com/micromark/micromark-extension-gfm-table/assets/88028913/d5a6f270-82ea-4d17-87f5-a5b7148bcb18)

![image](https://github.com/micromark/micromark-extension-gfm-table/assets/88028913/f071d033-a5d7-47ef-984d-7f08c22a76be)

### Runtime

Node v16

### Package manager

npm v7

### OS

Windows

### Build and bundle tools

Create React App

**Comment by wooorm** [comment]
> The code in codepen works

The codepen has static html? What is “work”?

---

This is how tables work. The alignment row has to have the same number of cells as the header row.

```markdown
| a | b |
| - |
```

| a | b |
| - |
