### ISSUE TITLE
Flow can interrupt tables

### ISSUE THREAD

**Issue by wooorm** [micromark/micromark-extension-gfm-table#4]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest

### Steps to reproduce

````markdown
| a |
| - |
| b |
> block quote?

| a |
| - |
| b |
- list?

| a |
| - |
| b |
<div>html?</div>

| a |
| - |
| b |
# atx heading

| a |
| - |
| b |
    indented code?

| a |
| - |
| b |
```js
fenced code?
```

| a |
| - |
| b |
***

^-- thematic break

| a |
| - |
| b |
paragraph?

| a |
| - |
| b |
[x]: definition

| a |
| - |
| b |
setext heading
===
````

### Expected behavior

| a |
| - |
| b |
> block quote?

| a |
| - |
| b |
- list?

| a |
| - |
| b |
<div>html?</div>

| a |
| - |
| b |
# atx heading

| a |
| - |
| b |
    indented code?

| a |
| - |
| b |
```js
fenced code?
```

| a |
| - |
| b |
***

^-- thematic break

| a |
| - |
| b |
paragraph?

| a |
| - |
| b |
[x]: definition

| a |
| - |
| b |
setext heading
===

### Actual behavior

https://github.com/syntax-tree/unist/discussions/57

**Comment by pjkaufman** [comment]
@wooorm , I am seeing an issue quite similar to this: https://github.com/remarkjs/remark/discussions/1003.

Is there a particular way I should go about creating a discussion/issue here on micromark-extension-gfm-table?

**Comment by wooorm** [comment]
This is a problem with [`micromark-extension-gfm-table`](https://github.com/micromark/micromark-extension-gfm-table) indeed. Can you open an issue here? Or a PR with a failing test?

**Comment by pjkaufman** [comment]
> This is a problem with [`micromark-extension-gfm-table`](https://github.com/micromark/micromark-extension-gfm-table) indeed. Can you open an issue here? Or a PR with a failing test?

I'll see about opening an issue.
